### PR TITLE
Added support for legacy encryption format

### PR DESCRIPTION
**Pull request by fastlorenzo**
This PR adds support for keys that were created using the legacy format.

Also included a small fix for decrypting files smaller than block size (headers were not parsed in that case).

### CODE REVIEW

**Comment by yahesh** [comment]
@fastlorenzo Thanks for your contribution. Do you know in which version of Owncloud/Nextcloud this legacy-legacy format was used? Until now I only had a look at release versions 16+.

**Comment by fastlorenzo** [comment]
That's quite old, installation dates from 2014/2015, so my guess is the initial version installed with encryption was Owncloud 7 or 8 😄 
I've got nearly all files covered now, still looking at a last issue for a few files which have a fileKey that cannot be decrypted by your tool, most probably some legacy edge cases as well.

**Comment by yahesh** [comment]
@fastlorenzo Wow, that's pretty ancient.

**Comment by fastlorenzo** [comment]
yes, just noticed that changing the parseHeader without any additional check is messing with the copying of non-encrypted files.. that might be the issue, will check and add to the PR.

**Comment by yahesh** [comment]
@fastlorenzo I now finally found the time to test your patch. Thanks again for the good work!

**Pull request merged**
